import type { LifeEvent } from './types'

export const LIFE_EVENTS: LifeEvent[] = [
  {
    id: 'one_child',
    label: '1 Child',
    description: 'Raising a child through school, college, and wedding — including tuition, activities, and living costs',
    icon: '👶',
    costLabel: '~₹3.5L/yr added to retirement goal',
    extraAnnualCost: () => 350000,
    corpusReduction: () => 0,
  },
  {
    id: 'two_children',
    label: '2 Children',
    description: 'Raising two children through school, college, and weddings',
    icon: '👶👶',
    costLabel: '~₹6L/yr added to retirement goal',
    extraAnnualCost: () => 600000,
    corpusReduction: () => 0,
  },
  {
    id: 'dependent_parent',
    label: 'Dependent Parent',
    description: 'Supporting an elderly parent for ~10 years covering medical, living, and care costs',
    icon: '👴',
    costLabel: '₹1.2L/yr for 10 years, plus ₹3L upfront setup',
    // ₹1.2L/yr ongoing care cost (realistic for Indian elderly care)
    extraAnnualCost: () => 120000,
    corpusReduction: () => 300000,
  },
  {
    id: 'home_purchase',
    label: 'Home Purchase',
    description: 'Down payment on a home before retirement — national average across Tier 1, 2, and 3 cities',
    icon: '🏠',
    costLabel: '₹50L one-time reduction to your savings',
    extraAnnualCost: () => 0,
    corpusReduction: () => 5000000,
  },
  {
    id: 'health_event',
    label: 'Major Health Event',
    description: 'Serious illness or surgery — e.g. cardiac, cancer, dialysis at a good hospital — including ongoing treatment',
    icon: '🏥',
    costLabel: '₹40L upfront + ₹1.5L/yr ongoing care',
    extraAnnualCost: () => 150000,
    corpusReduction: () => 4000000,
  },
  {
    id: 'job_loss',
    label: 'Job Loss / Career Break',
    description: 'Unemployment or career break of 1–2 years: missed investments, emergency expenses, and possible loan',
    icon: '💼',
    costLabel: '₹15L one-time reduction to your savings',
    extraAnnualCost: () => 0,
    corpusReduction: () => 1500000,
  },
  {
    id: 'divorce',
    label: 'Divorce / Separation',
    description: 'Legal costs, asset split, and potential alimony — significant one-time financial impact',
    icon: '⚖️',
    costLabel: '₹25L one-time reduction to your savings',
    extraAnnualCost: () => 0,
    corpusReduction: () => 2500000,
  },
  {
    id: 'disability',
    label: 'Disability / Long-term Illness',
    description: 'Permanent disability or chronic illness reducing earning ability and adding ongoing care costs',
    icon: '🩼',
    costLabel: '₹20L upfront + ₹1.2L/yr ongoing care',
    // Flat ₹1.2L/yr — this is a real recurring cost, not amortised over retirement
    extraAnnualCost: () => 120000,
    corpusReduction: () => 2000000,
  },
]
